---
title: "Couting Building in a City with Google Map ScreenShot"
output: flexdashboard::flex_dashboard
runtime: shiny
---


```{r global, include=FALSE}
library(flexdashboard)
library("EBImage")
```

Column {.sidebar}
-----------------------------------------------------------------------


```{r}
sliderInput("bw_adjust", label = "Frequency",
            min = 0.1, max = 0.9, value = 0.6, step = 0.1)
```

```{r}
## Choose an Image on your machine
city_image = readImage("1.png")


##To Choose your own Image uncomment this to select your own Image
##city_image = readImage(file.choose())
```

Row
-----------------------------------------------------------------------

### Geyser Eruption Duration

```{r global}
renderPlot({
        ImageofBuildingThreshol <- input$bw_adjust

        city_image_threshold <- city_image > ImageofBuildingThreshol

        building_count <- bwlabel(city_image_threshold)
        b_count <- max(building_count)
        
        display(city_image_threshold)
        
})
```
























